import tkinter as tk
racine=tk.Tk()

def affichage():
    """affiche la lettre sur le bouton"""
    global lettre
    label= tk.Label(racine, text=lettre,)

bouton_a = tk.Button(racine,text='A',command=affichage)
bouton_a.grid(column=0, row=0)
bouton_b = tk.Button(racine,text='B',command=affichage)
bouton_b.grid(column=1, row=0)
bouton_c = tk.Button(racine,text='C',command=affichage)
bouton_c.grid(column=2, row=0)
bouton_a = tk.Button(racine,text='D',command=affichage)
bouton_a.grid(column=3, row=0)
bouton_a = tk.Button(racine,text='E',command=affichage)
bouton_a.grid(column=4, row=0)
bouton_a = tk.Button(racine,text='F',command=affichage)
bouton_a.grid(column=5, row=0)
bouton_a = tk.Button(racine,text='G',command=affichage)
bouton_a.grid(column=6, row=0)
bouton_a = tk.Button(racine,text='H',command=affichage)
bouton_a.grid(column=7, row=0)
bouton_a = tk.Button(racine,text='I',command=affichage)
bouton_a.grid(column=8, row=0)
bouton_a = tk.Button(racine,text='J',command=affichage)
bouton_a.grid(column=9, row=0)
bouton_a = tk.Button(racine,text='K',command=affichage)
bouton_a.grid(column=10, row=0)
bouton_a = tk.Button(racine,text='L',command=affichage)
bouton_a.grid(column=11, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)
bouton_a = tk.Button(racine,text='M',command=affichage)
bouton_a.grid(colum=12, row=0)